<?php

namespace Database\Seeders;

use App\Models\WeddingPackage;
use Illuminate\Database\Seeder;

class WeddingPackageCatalogSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->packages() as $package) {
            WeddingPackage::query()->updateOrCreate(
                ['slug' => $package['slug']],
                $package,
            );
        }
    }

    /** @return list<array<string, mixed>> */
    private function packages(): array
    {
        return [
            $this->package(
                name: 'Peluk Kasih',
                slug: 'peluk-kasih',
                price: 17047000,
                tagline: 'PAKET KUMPLIT HARGA IRIT',
                description: 'Paket lengkap dengan dekorasi, makeup, acara, dokumentasi, vendor, dan term of payment yang jelas.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 6 m',
                        'Panggung pelaminan 2,5 x 6 m',
                        'Tenda 6 x 12 m',
                        'Sofa pengantin 1 set',
                        'Kotak amplop',
                        'Meja prasmanan 4 pcs',
                        'Meja penerima tamu 1 pcs, digunakan sesudah akad',
                        'Gazebo / tenda kecil ukuran 2 x 3 m untuk penerima tamu',
                        'Lorong segilima / besi kubah putih, kondisional',
                        'Alat makan 100 set: piring lidi, sendok/garpu',
                        'Alat prasmanan: sangku 1, pemanas kotak 5, pemanas sop 1',
                        'Dekor kain rumah untuk teras dan ruang tamu',
                        'Panggung hiburan 3 x 4 m',
                        'Kursi akad 6 pcs',
                        'Kursi tamu 70 pcs beserta cover',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 4 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Makeup ibu hajat',
                    ]),
                    $this->section('Acara', [
                        'MC, termasuk panduan sawer, sungkem, betot bakakak, huap lingkung, dan lain-lain',
                        'Hiburan organ: 2 penyanyi dan 1 pemain keyboard',
                        'Sound system, tidak termasuk acara pengajian',
                    ]),
                    $this->section('Dokumentasi', [
                        'Photographer 1 orang',
                        'Album magnetik',
                        'File melalui Google Drive',
                    ]),
                    $this->section('Vendor', [
                        'MUA: Gea Kamelia',
                        'Photographer: ID.Picture',
                        'MC: Sahlan Maulana',
                        'Hiburan: ABS Production',
                        'Henna: Nana Henna Art',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30% dari paket yang diambil',
                        'Item yang tidak tertera berarti belum termasuk paket',
                        'Pelunasan maksimal H-7 acara',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket wedding agar tidak terjadi kekeliruan',
                    ]),
                ],
                sortOrder: 1,
            ),
            $this->package(
                name: 'Selamanya',
                slug: 'selamanya',
                price: 26350000,
                tagline: 'HARGA PAS KUALITAS PUAS',
                description: 'Paket lengkap dengan dekorasi, makeup, upacara adat, dokumentasi, bonus, dan vendor rekomendasi.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 6 m',
                        'Stage 2,5 x 6 m',
                        'Tenda 8 x 12 m',
                        'Sofa pengantin 1 set',
                        'Kotak amplop 2 pcs',
                        'Meja prasmanan 4 pcs',
                        'Meja penerima tamu 1 pcs, digunakan setelah akad',
                        'Gazebo ukuran 2 x 3 m',
                        'Pergola',
                        'Alat makan 100 set',
                        'Alat prasmanan: sangku 1, pemanas kotak 5, pemanas sayur 1',
                        'Dekor kain rumah untuk teras dan ruang tamu',
                        'Panggung hiburan 3 x 4 m',
                        'Kursi akad 6 pcs',
                        'Kursi tamu 100 pcs beserta cover',
                        'Meja cemilan 2 pcs',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 4 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Makeup ibu hajat',
                        'Makeup ibu besan untuk domisili Cianjur dan lokasi yang terjangkau',
                    ]),
                    $this->section('Acara', [
                        'MC termasuk sawer, sungkem, betot bakakak, huap lingkung, dan lain-lain',
                        'Hiburan organ: 2 penyanyi, 1 pemain keyboard, 1 gendang, 2 operator sound',
                        'Sound system, tidak termasuk acara pengajian',
                        'Upacara adat / Lengser',
                    ]),
                    $this->section('Dokumentasi', [
                        'Photographer 1 orang',
                        'Album magazine 1 pcs',
                        'File melalui Google Drive',
                        'Videographer 1 orang',
                    ]),
                    $this->section('Bonus', [
                        'Softlens pengantin',
                        'Buket property foto',
                    ]),
                    $this->section('Vendor', [
                        'MUA: Ismawati',
                        'Request by Ahya: tambahan Rp500.000, ditampilkan sebagai catatan teks',
                        'Henna: Nana Henna Art',
                        'MC: Romli / Sri Astuti / Sahlan Maulana',
                        'Hiburan: ABS Production',
                        'Upacara Adat: Sanggar Mekar Arum / Getar Pasundan',
                        'Photographer: Ajwa Photo / Nice Picture',
                        'Videographer: Gallery.Adi',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket',
                        'DP hangus jika pembatalan dilakukan sepihak oleh client',
                    ]),
                ],
                sortOrder: 2,
            ),
            $this->package(
                name: 'Sapphire Soire',
                slug: 'sapphire-soire',
                price: 35000000,
                tagline: 'KUMPLIT ~ CUSTOM ~ LEGA',
                description: 'Paket luas dan fleksibel dengan dekorasi, makeup, upacara adat, entertainment, effect, bonus, dan dokumentasi.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 8 m',
                        'Stage 2,5 x 8 m',
                        'Tenda 8 x 20 m',
                        'Sofa pelaminan',
                        'Kotak amplop 2 pcs',
                        'Meja prasmanan',
                        'Meja penerima tamu',
                        'Gazebo',
                        'Pergola',
                        'Alat makan 150',
                        'Alat prasmanan',
                        'Panggung hiburan 3 x 4 m',
                        'Kursi akad 6 pcs',
                        'Kursi tamu 150 + cover',
                        'Backdrop photobooth',
                        'Stand cemilan 2 pcs',
                        'Lantai akrilik',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 6 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Pager bagus 2 pcs',
                        'Makeup ibu besan',
                    ]),
                    $this->section('Acara', [
                        'MC',
                        'Hiburan organ',
                        'Sound system, tidak termasuk pengajian',
                        'Lengser / Upacara Adat: Aki, Ambu, penari 4 orang, pemayung 1 orang',
                    ]),
                    $this->section('Dokumentasi', [
                        'Photographer 1 orang',
                        'Album magazine',
                        'Videographer',
                    ]),
                    $this->section('Entertainment', [
                        'Sound system',
                        'Organ atau akustik, client dapat memilih',
                    ]),
                    $this->section('Effect', [
                        'Lighting beam',
                    ]),
                    $this->section('Bonus', [
                        'Janur 1 pcs',
                        'Buku tamu 2 pcs',
                        'Tim WO on the day 3 orang',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket wedding',
                    ]),
                ],
                sortOrder: 3,
            ),
            $this->package(
                name: 'Sepenuh Hati',
                slug: 'sepenuh-hati',
                price: 20847000,
                tagline: 'PAKET KUMPLIT HARGA IRIT',
                description: 'Paket lengkap dengan dekorasi, makeup, upacara adat, dokumentasi, vendor, dan term of payment.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 6 m',
                        'Panggung pelaminan 2,5 x 6 m',
                        'Tenda 6 x 12 m',
                        'Sofa Patrik telur',
                        'Kotak amplop',
                        'Meja prasmanan 4 pcs',
                        'Meja penerima tamu 1 pcs, digunakan sesudah akad',
                        'Gazebo 2 x 3 m',
                        'Lorong segilima / besi kubah putih, kondisional',
                        'Alat makan 100 set',
                        'Alat prasmanan: sangku 1, pemanas kotak 5, pemanas sop 1',
                        'Dekor kain rumah',
                        'Panggung hiburan 3 x 4 m',
                        'Kursi akad 6 pcs',
                        'Kursi tamu 70 pcs beserta cover',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 4 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Makeup ibu hajat',
                    ]),
                    $this->section('Acara', [
                        'MC',
                        'Hiburan organ',
                        'Sound system, tidak termasuk acara pengajian',
                        'Lengser / Upacara Adat: Aki, Ambu, penari 4 orang, pemayung 1 orang',
                    ]),
                    $this->section('Dokumentasi', [
                        'Shoot sampai closing acara',
                        'Album magazine 1 pcs',
                        'File melalui Google Drive',
                    ]),
                    $this->section('Vendor', [
                        'MUA: Ismawati',
                        'Henna: Nana Henna Art',
                        'Photographer: Ajwa Photo / Nice Picture',
                        'Hiburan: ABS Production',
                        'Lengser: Getar Pasundan / Mekar Arum',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket wedding',
                    ]),
                ],
                sortOrder: 4,
            ),
            $this->package(
                name: 'Pelita Cinta',
                slug: 'pelita-cinta',
                price: 23890000,
                tagline: null,
                description: 'Paket wedding dengan dekorasi, makeup, acara, dokumentasi, bonus, vendor rekomendasi, dan term of payment.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 6 m',
                        'Stage 2,5 x 6 m',
                        'Tenda 8 x 12 m',
                        'Sofa pengantin 1 set',
                        'Kotak amplop 2 pcs',
                        'Meja prasmanan 4 pcs',
                        'Meja penerima tamu 1 pcs',
                        'Gazebo 2 x 3 m',
                        'Pergola',
                        'Alat makan 100 set',
                        'Alat prasmanan',
                        'Dekor kain rumah',
                        'Panggung hiburan 3 x 4 m',
                        'Kursi akad 6 pcs',
                        'Kursi tamu 100 pcs beserta cover',
                        'Meja cemilan 2 pcs',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 4 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Makeup ibu hajat',
                        'Makeup ibu besan untuk domisili Cianjur dan lokasi yang terjangkau',
                    ]),
                    $this->section('Acara', [
                        'MC',
                        'Hiburan organ',
                        'Sound system',
                        'Upacara Adat / Lengser',
                    ]),
                    $this->section('Dokumentasi', [
                        'Photographer 1 orang',
                        'Album magazine 1 pcs',
                        'File melalui Google Drive',
                    ]),
                    $this->section('Bonus', [
                        'Softlens pengantin',
                        'Buket property foto',
                    ]),
                    $this->section('Vendor', [
                        'MUA: Ismawati',
                        'Request by Ahya +Rp500.000 sebagai catatan teks',
                        'Henna: Nana Henna Art',
                        'MC: Romli / Sri Astuti / Sahlan Maulana',
                        'Hiburan: ABS Production',
                        'Upacara Adat: Sanggar Mekar Arum / Getar Pasundan',
                        'Photographer: Ajwa Photo / Nice Picture',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket wedding',
                        'DP hangus jika pembatalan dilakukan sepihak',
                    ]),
                ],
                sortOrder: 5,
            ),
            $this->package(
                name: 'Cahaya Bahagia',
                slug: 'cahaya-bahagia',
                price: 30400000,
                tagline: null,
                description: 'Paket wedding lengkap dengan dekorasi, makeup, acara, dokumentasi, entertainment, vendor, dan bonus.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 8 m',
                        'Stage 2,5 x 8 m',
                        'Tenda 8 x 12 m',
                        'Sofa pelaminan',
                        'Kotak amplop 2 pcs',
                        'Meja prasmanan',
                        'Meja penerima tamu',
                        'Gazebo',
                        'Pergola',
                        'Alat makan 150',
                        'Alat prasmanan',
                        'Panggung hiburan 3 x 4 m',
                        'Kursi akad 6 pcs',
                        'Kursi tamu 150 + cover',
                        'Backdrop photobooth',
                        'Stand cemilan 2 pcs',
                        'Lantai akrilik',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 6 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Pager bagus 1 pcs',
                        'Makeup ibu besan',
                    ]),
                    $this->section('Acara', [
                        'MC',
                        'Hiburan organ',
                        'Sound system',
                        'Lengser / Upacara Adat',
                    ]),
                    $this->section('Dokumentasi', [
                        'Photographer',
                        'Album magazine',
                        'Videographer',
                    ]),
                    $this->section('Entertainment', [
                        'Sound system',
                        'Organ / akustik, boleh pilih',
                    ]),
                    $this->section('Vendor', [
                        'MUA: Ismawati / Ahya',
                        'Henna: Nana Art',
                        'Photographer: Color Couple',
                        'Videographer: EU Film',
                        'Hiburan: Berlian Entertainment',
                        'Upacara Adat: Sanggar Seni Mekar Arum / Getar Pasundan',
                        'MC: Romli / Sri',
                    ]),
                    $this->section('Bonus', [
                        'Janur 1 pcs',
                        'Buku tamu 2 pcs',
                        'Tim WO on the day 3 orang',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket wedding',
                    ]),
                ],
                sortOrder: 6,
            ),
            $this->package(
                name: 'Rumah Kita',
                slug: 'rumah-kita',
                price: 12557000,
                tagline: 'Paket intimate wedding outdoor',
                description: 'Paket intimate wedding outdoor dengan dekorasi, makeup, bonus gratis, vendor, dan term of payment.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 6 m',
                        'Stage 2,5 x 6 m',
                        'Tenda 6 x 8 m',
                        'Sofa Ganesha putih',
                        'Kotak amplop',
                        'Meja prasmanan',
                        'Meja penerima tamu 1 pcs',
                        'Gazebo ukuran 2 x 3 m',
                        'Lorong segitiga menyesuaikan lokasi',
                        'Alat makan 100 set',
                        'Alat prasmanan',
                        'Dekor kain rumah',
                        'Kursi tamu 50 pcs tanpa cover',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 4 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Makeup ibu hajat, belum termasuk ibu besan',
                    ]),
                    $this->section('Gratis', [
                        'Photographer 2 Roll',
                        'Softlens pengantin',
                    ]),
                    $this->section('Vendor', [
                        'MUA: Gea Kamelia Makeup Artist',
                        'Henna: Nana Henna Art',
                        'Photographer: ID.Picture',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket',
                        'DP hangus jika pembatalan dilakukan sepihak',
                    ]),
                ],
                sortOrder: 7,
            ),
            $this->package(
                name: 'Janji Suci',
                slug: 'janji-suci',
                price: 6195000,
                tagline: null,
                description: 'Paket akad dengan dekorasi, MUA, busana, melati, softlens, henna, dan nail art.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 3 m, menyesuaikan space',
                        'Sofa pengantin',
                        'Karpet pelaminan',
                        'Lighting',
                        'Artificial flower',
                        'Welcome sign',
                        'Dekor kain rumah',
                        'Meja prasmanan 4 pcs',
                        'Alat makan 50 set',
                        'Alat prasmanan 7 pcs',
                        'Kursi akad 6 pcs',
                        'Meja akad 1 pcs',
                    ]),
                    $this->section('MUA', [
                        'MUA by Ismawati',
                        'Busana akad CPP & CPW',
                        'Melati asli',
                        'Softlens untuk mata normal',
                        'Henna & Nail Art',
                        'Kalung melati pria',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket',
                    ]),
                ],
                sortOrder: 8,
            ),
            $this->package(
                name: 'Emerald Wedding By Atha',
                slug: 'emerald-wedding-by-atha',
                price: 55000000,
                tagline: null,
                description: 'Paket premium dengan dekorasi custom, makeup, upacara adat, entertainment, catering, bonus, dan dokumentasi.',
                sections: [
                    $this->section('Dekorasi', [
                        'Pelaminan 8-10 m',
                        'Stage 3 x 8 m',
                        'Tenda 8 x 12 m',
                        'Sofa kerang',
                        'Kotak amplop 2 pcs',
                        'Meja prasmanan',
                        'Meja penerima tamu 2 pcs',
                        'Gazebo',
                        'Lorong putih',
                        'Gate wedding',
                        'Lantai jalan melamin',
                        'Panggung hiburan 4 x 6 m',
                        'Set akad',
                        'Kursi tamu 150 + cover',
                        'Photobooth',
                        'Stand cemilan 2 pcs',
                        'Lighting dekorasi',
                        'Bebas request design dan konsep dengan minimal booking 2 bulan sebelumnya',
                    ]),
                    $this->section('Makeup', [
                        'Makeup and touch up',
                        'Hijab dan siger Sunda',
                        'Baju pengantin 2 kali',
                        'Baju orang tua dan besan',
                        'Baju & Makeup dayang 6 orang',
                        'Melati full set',
                        'Kalung melati pria',
                        'Henna & Nail Art',
                        'Pager bagus 2 pcs',
                        'Makeup ibu besan',
                    ]),
                    $this->section('Acara', [
                        'MC',
                        'Sound system',
                        'Upacara Adat: Lengser & penari',
                    ]),
                    $this->section('Dokumentasi', [
                        'Photographer 3 Roll',
                        'Album magazine',
                        'Videographer',
                    ]),
                    $this->section('Entertainment', [
                        'Akustik: player, singer, saxophone',
                        'Dan/atau organ dangdut rampak',
                    ]),
                    $this->section('Catering', [
                        '500 pack',
                        'Gubukan 2 macam',
                    ]),
                    $this->section('Bonus', [
                        'Janur 2 pcs',
                    ]),
                    $this->section('Term of Payment', [
                        'Booking 30%',
                        'Item yang tidak tertera belum termasuk paket',
                        'Pelunasan maksimal H-7',
                        'Tidak ada negosiasi ulang setelah dealing',
                        'Client wajib memahami isi paket wedding',
                        'Pembatalan sepihak tanpa kesepakatan menyebabkan DP hangus',
                    ]),
                ],
                sortOrder: 9,
            ),
        ];
    }

    /** @param list<array{title: string, items: list<string>}> $sections */
    private function package(
        string $name,
        string $slug,
        int $price,
        ?string $tagline,
        string $description,
        array $sections,
        int $sortOrder,
    ): array {
        return [
            'name' => $name,
            'slug' => $slug,
            'tagline' => $tagline,
            'description' => $description,
            'sections' => $sections,
            'price' => $price,
            'is_active' => true,
            'sort_order' => $sortOrder,
        ];
    }

    /** @param list<string> $items */
    private function section(string $title, array $items): array
    {
        return [
            'title' => $title,
            'items' => $items,
        ];
    }
}
